### ISSUE TITLE
Evaluation score larger than 1

### ISSUE THREAD

**Issue by nightdessert** [salesforce/QAFactEval#1]
Hi, thanks for the very nice work!
I notice in  datasets like CNN/DM the tested QAFactEval score of  samples is larger that 1.
It is a little weird for a metric.
Is there any way I can normalize the evaluation scores in [0, 1] ?

**Comment by Alex-Fabbri** [comment]
Hi, 
Thanks for your interest in our work! The scores range from 0 to about 5 (some are greater than 5 although the MOCHA dataset has labels 1 to 5) so you can clip them at 5 and divide by 5 to get a score in [0, 1] .

**Comment by nightdessert** [comment]
> Hi, Thanks for your interest in our work! The scores range from 0 to about 5 (some are greater than 5 although the MOCHA dataset has labels 1 to 5) so you can clip them at 5 and divide by 5 to get a score in [0, 1] .

Thank you for answering. I have another question.
What is the best settings of the metric?The sample given in readme calculate with 'score_batch' function and sets "use_lerc_quip": True, while  the sample given in run.py calculate with 'score_batch_qafacteval' and sets "use_lerc_quip":  to False in default.

**Comment by Alex-Fabbri** [comment]
Thanks for pointing this out! The metric should uses score_batch_qafacteval with use_lerc_quip set to True; I've updated the files. Let me know if you have any other questions!
