### ISSUE TITLE
pip error: conflicting dependencies

### ISSUE THREAD

**Issue by Tan-Hexiang** [salesforce/QAFactEval#2]
Thanks for your great work!
i am trying to install qafacteval using `pip install -e .`and `pip install qafacteval`.
But I get the same error as follows.
There appears to be a dependency conflict. what should i do to solve this problem？

`pip install -e .
Obtaining file:///Users/tanhexiang/workplace/QAFactEval
  Preparing metadata (setup.py) ... done
Collecting qaeval
  Using cached qaeval-0.1.0-py3-none-any.whl (42 kB)
  Using cached qaeval-0.0.9-py3-none-any.whl (36 kB)
  Using cached qaeval-0.0.8-py3-none-any.whl (36 kB)
  Using cached qaeval-0.0.7-py3-none-any.whl (28 kB)
Collecting urllib3>=1.25.10
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting allennlp==1.1.0
  Using cached allennlp-1.1.0-py3-none-any.whl (485 kB)
Collecting qaeval
  Using cached qaeval-0.0.6-py3-none-any.whl (26 kB)
  Using cached qaeval-0.0.5-py3-none-any.whl (26 kB)
  Using cached qaeval-0.0.3-py3-none-any.whl (18 kB)
  Using cached qaeval-0.0.2-py3-none-any.whl (18 kB)
  Using cached qaeval-0.0.1-py3-none-any.whl (18 kB)
INFO: pip is looking at multiple versions of qafacteval to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install qafacteval because these package versions have conflicting dependencies.

The conflict is caused by:
    qaeval 0.1.0 depends on torch==1.6.0
    qaeval 0.0.9 depends on torch==1.6.0
    qaeval 0.0.8 depends on torch==1.6.0
    qaeval 0.0.7 depends on torch==1.6.0
    qaeval 0.0.6 depends on torch==1.6.0
    qaeval 0.0.5 depends on torch==1.6.0
    qaeval 0.0.3 depends on torch==1.6.0
    qaeval 0.0.2 depends on torch==1.6.0
    qaeval 0.0.1 depends on torch==1.6.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by Tan-Hexiang** [comment]
I use python==3.6 instead of 3.10, and it works. Maybe, it was the newest python that caused this problem

**Comment by Alex-Fabbri** [comment]
That might be it - the python version I was running it with was 3.8.13. Closing this for now, but feel free to reopen if there are related issues!

**Comment by tomhosking** [comment]
Having the same issue with python 3.9 - it looks like `qaeval` requires `torch==1.6.0` which is not available for 3.9+.
