### ISSUE TITLE
Using QAFactEval for summarization evaluation

### ISSUE THREAD

**Issue by yfqiu98** [salesforce/QAFactEval#6]
Hi there, thank you very much for this nice work!

I would like to ask what is the best practice for using QAFactEval as the evaluation for multiple pairs of document and generated summary? I see the input format from the example is ```["doc1"]``` and ```[["summary1"]]```,
```
results = metric.score_batch_qafacteval(["This is a source document"], [["This is a summary."]], return_qa_pairs=True)
```
If I have multiple pairs of document and summary, is the input format like ```["doc1", "doc2"]``` and ```[["summary1"], ["summary2"]]```?
Also, I am wondering why we use a list of list for summary here, if I have a summary with multiple sentences, should I split it in the inside list, i.e., ```[["summary1_sent1", "summary1_sent2"], ["summary2_sent1", "summary2_sent2"]]```?

Thank you in advance.

**Comment by Alex-Fabbri** [comment]
Thank you for your interest in our work! 

Yes that's correct regarding the format if you have multiple summary-document pairs. 

The list of lists for summary is used here just to following the format of the underlying QAEval metric - for QAEval questions are generated based on a reference (or references) and answered using the summary model output, so the metric takes in multiple reference summaries as in `["summ1", "summ2"]` and `[["ref1_for_summ1", "ref2_for_summ1"], ["ref1_for_summ2", "ref2_for_summ2"]]`. This multi-reference format isn't needed here, so you don't need to separate your summary if it has multiple sentences.

**Comment by yfqiu98** [comment]
Thanks, you solve my issue :)
