### ISSUE TITLE
Generating questions on summary and not source

### ISSUE THREAD

**Issue by saxenarohit** [salesforce/QAFactEval#7]
```
  if qa_pairs_precomputed:
      qa_pairs_lists = qa_pairs_precomputed
  else:
      qa_pairs_lists = self._generate_qa_pairs(summaries)

```

Generating QA pairs from the summary. It should be source documents (reference summary)?

**Comment by Alex-Fabbri** [comment]
Hi! Thank you for your interest in our work. 
In our approach we generate QA pairs from the model summaries as in the code and check their answerability using the source document. 
Please check the below image from our paper. 
<img width="470" alt="image" src="https://user-images.githubusercontent.com/6563196/213191791-0317f5d7-2054-44b4-8f11-d46d0b13c41c.png">

**Comment by saxenarohit** [comment]
Thanks for your reply. Yes, sorry for the confusion. I wanted to compare the method with qaeval which compares candidate summaries with reference summaries. I will close the issue.
