### ISSUE TITLE
QAFactEval vs QAFactEval-NLI

### ISSUE THREAD

**Issue by sanjanaramprasad** [salesforce/QAFactEval#8]
Hi,

Thanks for your work in making this public! I'm trying to reproduce results using QAFactEval without NLI. I'm unable to decipher from the instructions if there are different models or settings to implement these. Could you point me to what I'd have to modify? Thanks for your time!

**Comment by Alex-Fabbri** [comment]
Hi, thank you for your interest in our work! The current release does not include the NLI part, so you should be able to reproduce that with this release. Please let me know if you have other questions.

**Comment by sanjanaramprasad** [comment]
Thanks for your response! I've been trying to reproduce the results reported in the QAFactEval_score column in this dataset -- https://github.com/Liyan06/AggreFact/blob/main/data/aggre_fact_final.csv 

I seem to get different numbers than what's reported. Could you maybe run for a couple and confirm? 
I'm mostly trying to disambiguate whether they've perhaps reported on an older version or if I'm doing something wrong with running the repository.

**Comment by Alex-Fabbri** [comment]
I ran on 10 examples and I believe those AggreFact results are obtained with the original lerc metric and not lerc_quip, so to reproduce that you can just set `use_lerc_quip` to `False`.
